import React from "react";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import {
    SlSocialInstagram,
    SlSocialYoutube,
    SlSocialFacebook,
    SlSocialTwitter,
} from "react-icons/sl";

import Wrapper from "@/components/wrapper";

const about = () => {

    const socialIcons = [
        {
            id: 1,
            icons: <SlSocialInstagram />,
            url: "https://www.instagram.com/",
        },
        {
            id: 2,
            icons: <SlSocialYoutube />,
            url: "https://www.instagram.com/",
        },
        {
            id: 3,
            icons: <SlSocialFacebook />,
            url: "https://www.instagram.com/",
        },
        {
            id: 4,
            icons: <SlSocialTwitter />,
            url: "https://www.instagram.com/",
        },
    ];

    return (
        <>
            <Head>
                <title>About Us - Kesha Jewellery</title>
                <meta name="description" content="Generated by create next app" />
            </Head>

            <Wrapper>
                <section className="p-5 flex-col md:flex lg:flex-row items-start justify-center gap-10 md:mt-[10px] lg:mt-[130px] mt-[100px]">
                    <section className="img rounded-md">
                        <Image src={`/category/1.png`} width={4000} height={4000} alt="about" className="rounded-md"/>
                    </section>
                    <section className="info mt-5 md:mt-0">
                        <h1 className="flex items-center mb-8 left-5 text-5xl font-oswald font-medium dark:text-black ">
                            About Us
                        </h1>
                        <p>
                            We have been producing handmade men's jewelry designs as
                            Bysilverstone for a long time and now you can explore our store to
                            buy a specially designed piece for your loved ones and yourself.
                            Jewelry is our family profession. We have worked as production
                            responsibly and we have manufactured products for premier brands
                            for years in Istanbul Grand Bazaar.
                            <br />
                            <br />
                            We started to sell our own products after hard work over two years
                            in R&D and market research. We have created the necessary
                            infrastructure to provide you always the newest models, matchless
                            designed products, and the fastest delivery system. We make
                            shipping the purchased product in only 1-2 days. We guarantee that
                            we do not compromise our services. Hereby, we hope you make the
                            people you loved happy by buying a Bysilverstone design because we
                            have made effort to make you and your favorite people happy.
                        </p>
                        <br />
                        <hr />
                        <h2 className="flex items-center text-2xl mt-[20px]  font-oswald font-medium dark:text-black ">
                            Kesha Jewellery Design LLC
                        </h2>
                        <br />
                        <p>Manufacturing - ByKeshaJewellery !!</p>
                        <br />
                        <p>
                        Malviya Nagar, Jaipur, Rajasthan 302017
                        </p>
                        <br />
                        <p>Jaipur | India</p>
                        {/* // */}
                        <br />
                        <hr />
                        <div className="social-icons flex items-center gap-6 my-[30px]">
                            {socialIcons.map((elm) => {
                                return (
                                    <>
                                        <Link
                                            href={`${elm.url}`}
                                            className="h-[32px] md:h-[32px] min-w-[32px] md:min-w-[32px] rounded-full bg-black top-1 left-5 md:left-7 text-white text-[16px] md:text-[16px] flex justify-center items-center px-[2px] md:px-[5px] hover:bg-red-400 hover:text-black"
                                        >
                                            {elm.icons}
                                        </Link>
                                    </>
                                );
                            })}
                        </div>
                        {/* // */}
                    </section>
                </section>
            </Wrapper>
        </>
    );
};

export default about;